import fs from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import type { EditorChange, EditorPatch, StyleChange } from "@/lib/editor/types";

type ApplyRequest = {
  patches?: EditorPatch[];
};

const outputPath = path.join(process.cwd(), "public", "editor-patches.css");

function toCssProperty(property: string) {
  return property.replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`);
}

function cssEscapeString(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\*\//g, "*\\/");
}

function routeComment(route: string) {
  return cssEscapeString(route || "/");
}

function selectorComment(selector: string) {
  return cssEscapeString(selector);
}

function cssValue(value: string) {
  return value.trim();
}

function styleDeclaration(change: StyleChange) {
  const value = cssValue(change.after);
  const property = toCssProperty(change.property);

  if (!value) return `${property}: initial !important;`;
  return `${property}: ${value} !important;`;
}

function unsupportedChange(change: EditorChange) {
  if (change.kind === "content") return change.field;
  if (change.kind === "element") return change.action;
  return null;
}

function cssForPatch(patch: EditorPatch) {
  const declarations: string[] = [];
  const unsupported: string[] = [];

  for (const change of patch.changes) {
    if (change.kind === "style") declarations.push(styleDeclaration(change));
    else if (change.kind === "element" && change.action === "hide" && change.after) {
      declarations.push("visibility: hidden !important;");
    } else if (change.kind === "element" && change.action === "delete" && change.after) {
      declarations.push("display: none !important;");
    } else {
      const label = unsupportedChange(change);
      if (label) unsupported.push(label);
    }
  }

  if (declarations.length === 0) return { css: "", unsupported };

  const css = [
    `/* ${routeComment(patch.route)} :: ${selectorComment(patch.target.selector)} */`,
    `${patch.target.selector} {`,
    ...declarations.map((declaration) => `  ${declaration}`),
    "}",
  ].join("\n");

  return { css, unsupported };
}

function buildEditorPatchCss(patches: EditorPatch[]) {
  const cssBlocks: string[] = [
    "/* Generated by the local visual editor. Do not edit by hand. */",
    `/* Updated: ${new Date().toISOString()} */`,
  ];
  const unsupported: Array<{ selector: string; changes: string[] }> = [];
  let applied = 0;

  for (const patch of patches) {
    const result = cssForPatch(patch);
    if (result.css) {
      cssBlocks.push("", result.css);
      applied += 1;
    }
    if (result.unsupported.length > 0) {
      unsupported.push({
        selector: patch.target.selector,
        changes: result.unsupported,
      });
    }
  }

  return {
    applied,
    css: `${cssBlocks.join("\n")}\n`,
    unsupported,
  };
}

export async function POST(request: Request) {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json({ message: "Editor patching is disabled in production." }, { status: 403 });
  }

  const body = (await request.json().catch(() => ({}))) as ApplyRequest;
  const patches = Array.isArray(body.patches) ? body.patches : [];
  const result = buildEditorPatchCss(patches);

  await fs.writeFile(outputPath, result.css, "utf8");

  return NextResponse.json({
    ok: true,
    applied: result.applied,
    unsupported: result.unsupported,
    file: "public/editor-patches.css",
  });
}
